service: crud-to-do

frameworkVersion: ^3.22.0

plugins:
  - serverless-iam-roles-per-function

package:
  individually: true
  excludeDevDependencies: false
  patterns:
    - '!node_modules/**'
    - '!.vscode/**'
    - '!.pytest_cache/**'
    - '!src/__pycache__'
    - '!tests/__pycache__'
    - '!src/**/__pycache__'
    - '!tests/**/__pycache__'
    - '!./**'
    - '!tests/**'
    - src/**

provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: 'sa-east-1'
  logRetentionInDays: 7
  environment:
    TABLE_NAME: tasks
    ACCOUNT_ID: ${aws:accountId}

custom:
  aws_config:
    aws_account_id: ${self:provider.environment.ACCOUNT_ID}
  table_config:
    table_name: ${self:provider.environment.TABLE_NAME}
    table_arn: arn:aws:dynamodb:${self:provider.region}:${self:provider.environment.ACCOUNT_ID}:table/${self:provider.environment.TABLE_NAME}

functions:
  - ${file(src/handlers/tasks/routes.yml)}
