service: crud-to-do

frameworkVersion: ^3.22.0

# plugins:
#   - serverless-localstack

package:
  individually: true
  excludeDevDependencies: false
  patterns:
    - '!node_modules/**'
    - '!.vscode/**'
    - '!.pytest_cache/**'
    - '!src/__pycache__'
    - '!tests/__pycache__'
    - '!src/**/__pycache__'
    - '!tests/**/__pycache__'
    - '!./**'
    - '!tests/**'
    - src/**

custom:
  awsconfig:
    aws_account_id: 974211203733
    aws_role_lambda: LambdaDynamoTasksRole

provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: 'sa-east-1'
  logRetentionInDays: 7

functions:
  - ${file(src/handlers/tasks/routes.yml)}
