createTask:
  handler: src/services/tasks/handlers/create.lambda_handler
  events:
    - http:
        path: tasks
        method: post
  package:
    patterns:
      - ../../../src/services/tasks/handlers/create.py
      - ../../../src/services/tasks/use_cases/create_task.py
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - ${self:custom.table_config.table_arn}
fetchTasks:
  handler: src/services/tasks/handlers/fetch.lambda_handler
  events:
    - http:
        path: tasks
        method: get
  package:
    patterns:
      - ../../../src/services/tasks/handlers/fetch.py
      - ../../../src/services/tasks/use_cases/fetch_tasks.py
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
      Resource:
        - ${self:custom.table_config.table_arn}
findTask:
  handler: src/services/tasks/handlers/find.lambda_handler
  events:
    - http:
        path: tasks/{id}
        method: get
  package:
    patterns:
      - ../../../src/services/tasks/handlers/find.py
      - ../../../src/services/tasks/use_cases/find_task.py
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource:
        - ${self:custom.table_config.table_arn}
completeTask:
  handler: src/services/tasks/handlers/complete.lambda_handler
  events:
    - http:
        path: tasks/{id}/complete
        method: patch
  package:
    patterns:
      - ../../../src/services/tasks/handlers/complete.py
      - ../../../src/services/tasks/use_cases/complete_task.py
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:UpdateItem
      Resource:
        - ${self:custom.table_config.table_arn}
updateTask:
  handler: src/services/tasks/handlers/update.lambda_handler
  events:
    - http:
        path: tasks/{id}
        method: put
  package:
    patterns:
      - ../../../src/services/tasks/handlers/update.py
      - ../../../src/services/tasks/use_cases/update_task.py
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:UpdateItem
      Resource:
        - ${self:custom.table_config.table_arn}
deleteTask:
  handler: src/services/tasks/handlers/delete.lambda_handler
  events:
    - http:
        path: tasks/{id}
        method: delete
  package:
    patterns:
      - ../../../src/services/tasks/handlers/delete.py
      - ../../../src/services/tasks/use_cases/delete_task.py
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
      Resource:
        - ${self:custom.table_config.table_arn}