service: login-service

frameworkVersion: ^3.22.0

plugins:
  - serverless-iam-roles-per-function

package:
  individually: true
  excludeDevDependencies: false
  patterns:
    - '!node_modules/**'
    - '!.vscode/**'
    - '!.github/**'
    - '!.pytest_cache/**'
    - '!src/__pycache__'
    - '!src/**/__pycache__'
    - '!./**'
    - '!tests/**'
    - '!config/**'

custom:
  aws_config: ${file(../../../config/aws-config.yml):aws_config}
  table_config:
    table_name: users
    table_arn: arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/users

provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: 'sa-east-1'
  logRetentionInDays: ${self:custom.aws_config.log_retention_in_days}

functions:
  - ${file(routes.yml)}
